accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import contact.urls
from . import views

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^', include(contact.urls, namespace='contact')),
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^', include(wagtail_urls)),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

news/models.py
from django import forms
from django.db import models

# New imports added for ClusterTaggableManager, TaggedItemBase, MultiFieldPanel

from modelcluster.fields import ParentalKey, ParentalManyToManyField
from modelcluster.contrib.taggit import ClusterTaggableManager
from taggit.models import TaggedItemBase

from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, InlinePanel, MultiFieldPanel
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsearch import index
from wagtail.wagtailsnippets.models import register_snippet

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@register_snippet
class NewsCategory(models.Model):
    name = models.CharField(max_length=255)
    icon = models.ForeignKey(
        'wagtailimages.Image', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='+'
    )

    panels = [
        FieldPanel('name'),
        ImageChooserPanel('icon'),
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'news categories'


class NewsIndexPage(Page):
    intro = RichTextField(blank=True)

    def get_context(self, request):
        context = super(NewsIndexPage, self).get_context(request)

        # Get the full unpaginated listing of resource pages as a queryset -
        # replace this with your own query as appropriate
        blogpages = self.get_children().live().order_by('-first_published_at')

        paginator = Paginator(blogpages, 3) # Show 3 resources per page

        page = request.GET.get('page')
        try:
            blogpages = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            blogpages = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            blogpages = paginator.page(paginator.num_pages)

        # make the variable 'resources' available on the template
        context['blogpages'] = blogpages

        return context


class NewsPageTag(TaggedItemBase):
    content_object = ParentalKey('NewsPage', related_name='tagged_items')

class NewsTagIndexPage(Page):

    def get_context(self, request):

        # Filter by tag
        tag = request.GET.get('tag')
        blogpages = NewsPage.objects.filter(tags__name=tag)

        # Update template context
        context = super(NewsTagIndexPage, self).get_context(request)
        context['blogpages'] = blogpages
        return context

class NewsPage(Page):
    date = models.DateField("Post date")
    intro = models.CharField(max_length=250)
    body = RichTextField(blank=True)
    tags = ClusterTaggableManager(through=NewsPageTag, blank=True)
    categories = ParentalManyToManyField('news.NewsCategory', blank=True)

    def main_image(self):
        gallery_item = self.gallery_images.first()
        if gallery_item:
            return gallery_item.image
        else:
            return None

    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('date'),
            FieldPanel('tags'),
            FieldPanel('categories', widget=forms.CheckboxSelectMultiple),
        ], heading="News information"),
        FieldPanel('intro'),
        FieldPanel('body'),
        InlinePanel('gallery_images', label="Gallery images"),
    ]

class NewsPageGalleryImage(Orderable):
    page = ParentalKey(NewsPage, related_name='gallery_images')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption'),
    ]

news/templates/news/news_index_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% load thumbnail %}

{% block body_class %}template-blogindexpage{% endblock %}

{% block container %}
<section class="news-index-page">
  <div class="container">
    <div class="row">
      <div class="col-md-8 post-index-article">

      <h1 class="text-center">{{ page.title }}</h1>
      <div class="intro">{{ page.intro|richtext }}</div>

      {% for post in blogpages %}
          {% with post=post.specific %}
              <h2 class="text-center"><a href="{% pageurl post %}">{{ post.title }}</a></h2>

              {% with post.main_image as main_image %}
                  {% if main_image %}{% image main_image width-600 %}{% endif %}
              {% endwith %}

              <p class="text-center">{{ post.intro }}</p>
              {{ post.body|richtext|truncatewords_html:50 }}
              <a class="btn btn-primary" href="{% pageurl post %}">Read More &raquo;</a>
              <hr>

          {% endwith %}
      {% endfor %}

      <div class="row">
  <div class="col-md-12">
    <ul class="pagination">
      {% if blogpages.has_previous %}
        <li>
          <a href="?page={{ blogpages.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
        </li>
      {% endif %}
      {% for page_num in blogpages.paginator.page_range %}
        <li {% if page_num == blogpages.number %} class="active"{% endif %}>
          <a href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
      {% endfor %}
      {% if resources.has_next %}
        <li>
          <a href="?page={{ blogpages.next_page_number }}"><i class="fa fa-angle-right"></i></a>
        </li>
        {% endif %}
    </ul>
  </div>
</div>
      </div>

      <div class="col-md-4 sidebar">



        <div class="profile-sidebar">
        				<!-- END SIDEBAR USERPIC -->
        				<!-- SIDEBAR USER TITLE -->
        					<div class="sidebar-user text-center">
                    {% if user.is_authenticated %}
        						  <h3>Welcome {{ user.get_full_name }}</h3>
                      <p>We're glad you're here!</p>
                    {% else %}
                      <h3>Welcome Guest</h3>
        						<p>Please sign in or sign up.</p>
                    {% endif %}
                    <p>Today is: {% now 'd M, Y' %}</p>

        					</div>
        				<!-- END SIDEBAR USER TITLE -->
        				<!-- SIDEBAR BUTTONS -->
        				<div class="profile-userbuttons">
                  {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'profiles:show_self' %}" role="button">Profile</a>
                    <a class="btn btn-default" href="{% url 'accounts:logout' %}?next={{request.path}}" role="button">Sign Out</a>
                      {% else %}
                    <a class="btn btn-primary" href="{% url 'accounts:login' %}?next={{request.path}}" role="button">Sign In</a>
                    <a class="btn btn-default" href="{% url 'accounts:signup' %}?next={{request.path}}" role="button">Sign Up</a>
                  {% endif %}
                  <hr>
        				</div>
        				<!-- END SIDEBAR BUTTONS -->
        				<!-- SIDEBAR MENU -->
                <div class="row">

                <div class="col-md-8 col-md-offset-2">
        				<div class="profile-usermenu">
                  <h3 class="text-center">Navigation</h3>
        					<ul class="nav">
        						<li class="active">
        							<a href="/">
        							<i class="glyphicon glyphicon-home"></i>
        							Home </a>
        						</li>
        						<li>
        							<a href="/#features">
        							<i class="glyphicon glyphicon-user"></i>
        							Features </a>
        						</li>
        						<li>
        							<a href="/#gallery" target="_blank">
        							<i class="glyphicon glyphicon-picture"></i>
        							Gallery </a>
        						</li>
        						<li>
        							<a href="/#contact">
        							<i class="glyphicon glyphicon-envelope"></i>
        							Contact </a>
        						</li>
        					</ul>
        				</div>
              </div>
            </div>
            <hr>
        			<!-- END MENU -->
        			</div>

          <div class="col-md-12 text-center">
            <h3 class="text-center">Subscribe Now</h3>
            <p class="text-justify mb-25">Subscribe to our company newsletter and be the first to get the latest and greatest news as it happens.</p>
            <a class="btn btn-primary" href="/subscribe/">SUBSCRIBE</a>
            <hr>
        </div>

        <div class="col-md-12 text-center">
          <h3 class="mb-25">About Us</h3>
          <img class="mb-25" style="border:10px solid #f5f5f5;box-shadow: 0 0 1px #999;" src="http://placehold.it/175x175" />
          <p class="text-justify">Cras dapibus. Etiam iaculis nunc ac metus. Suspendisse pulvinar, augue ac venenatis condimentum, sem libero volutpat nibh, nec pellentesque velit pede quis nunc. Praesent nec nisl a purus blandit viverra. Fusce egestas elit eget lorem. Nullam tincidunt adipiscing enim.</p>
          <hr>
        </div>

        <div class="col-md-12">
          <h3 class="mb-25 text-center">Social media</h3>
          <ul class="social-network social-circle text-center">
              <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
              <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
              <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
          </ul>
          <hr>
        </div>

        <div class="col-md-12 gallery">
          <h3 class="mb-25 text-center">Gallery</h3>
          <div class="row mb-25">
            <div class="col-md-6">
              <img class="img-responsive" src="http://placehold.it/200x200" />
            </div>
            <div class="col-md-6">
              <img class="img-responsive" src="http://placehold.it/200x200" />
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <img class="img-responsive" src="http://placehold.it/200x200" />
            </div>
            <div class="col-md-6">
              <img class="img-responsive" src="http://placehold.it/200x200" />
            </div>
          </div>
          <hr>
        </div>

        </div>

    </div>
  </div>
</section>
{% endblock %}

news/templates/news/news_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block body_class %}template-blogpage{% endblock %}

{% block container %}
<section class="news-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <h1>{{ page.title }}</h1>
        <p class="meta">{{ page.date }}</p>

<!--        {% with categories=page.categories.all %}
      {% if categories %}
          <h3>Posted in:</h3>
          <ul>
              {% for category in categories %}
                  <li style="display: inline">
                      {% image category.icon fill-32x32 style="vertical-align: middle" %}
                      {{ category.name }}
                  </li>
              {% endfor %}
          </ul>
      {% endif %}
  {% endwith %}
-->
        <div class="intro">{{ page.intro }}</div>
        {% for item in page.gallery_images.all %}
            <div class="post-image">
                {% image item.image width-600 %}
                <p class="post-image-caption text-center">{{ item.caption }}</p>
            </div>
        {% endfor %}

        {{ page.body|richtext }}



        <p><a class="btn btn-primary" href="{{ page.get_parent.url }}">News Page</a>
        <a class="btn btn-default" href="/">Home Page</a></p>

<!--        {% if page.tags.all.count %}
      <div class="tags">
          <h3>Tags</h3>
          {% for tag in page.tags.all %}
              <a href="{% slugurl 'tags' %}?tag={{ tag }}"><button type="button">{{ tag }}</button></a>
          {% endfor %}
      </div>
  {% endif %}
-->
      </div>
    </div>
  </div>
</section>
{% endblock %}

news/templates/news/news_tag_index_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}

{% block container %}
<section class="tags">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        {% if request.GET.tag|length %}
            <h4>Showing pages tagged "{{ request.GET.tag }}"</h4>
        {% endif %}

        {% for blogpage in blogpages %}

              <p>
                  <strong><a href="{% pageurl blogpage %}">{{ blogpage.title }}</a></strong><br />
                  <small>Revised: {{ blogpage.latest_revision_created_at }}</small><br />
                  {% if blogpage.author %}
                    <p>By {{ blogpage.author.profile }}</p>
                  {% endif %}
              </p>

        {% empty %}
            No pages found with that tag.
        {% endfor %}

      </div>
    </div>
  </div>
</section>
{% endblock %}